/*------------------------------------------------------------
Author:        Mohit Jain
Company:       Salesforce
Description:   Controller Class to show list of Coach on Coach Bios page
Inputs:                      
Test Class:    
History
14/03/2024      Mohit Jain    New Class Created for PR972315-16
------------------------------------------------------------*/
public class FEP_GetAppointmentSlotWrapper {
 
    public String territoryId;
    public String startTime;
    public String endTime;
    public Integer remainingAppointments;
    
}