import { createElement } from 'lwc';
import Fep_appointmentListCancelActionModal from 'c/fep_appointmentListCancelActionModal';

describe('c-fep-appointment-list-cancel-action-modal', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-fep-appointment-list-cancel-action-modal', {
            is: Fep_appointmentListCancelActionModal
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});